# Generated by Django 6.1 on 2026-08-24 10:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField(help_text='Odometer reading in km')),
                ('accident_history', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('service_records', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('ownership', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd+', '3rd owner or more')], max_length=10)),
                ('insurance_status', models.CharField(choices=[('valid', 'Valid'), ('expired', 'Expired')], max_length=10)),
                ('estimated_price_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_price_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('depreciation_adjustment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mileage_adjustment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('condition_adjustment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('lead_captured', 'Lead Captured'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('converted', 'Converted')], default='lead_captured', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
