# Generated by Django 6.1 on 2026-08-25 13:28
#
# Extends the existing Lead model (rather than adding a new DealerLead
# model) to support the /dealers/ signup form: adds `source` to distinguish
# dealer-signup leads from price-estimator leads, and relaxes the
# vehicle/condition/estimate fields to optional since dealer leads only
# populate phone/name.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('price_estimator', 'Price Estimator'), ('dealer_signup', 'Dealer Signup')], default='price_estimator', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='accident_history',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='condition_adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='depreciation_adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='estimated_price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='estimated_price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='insurance_status',
            field=models.CharField(blank=True, choices=[('valid', 'Valid'), ('expired', 'Expired')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='mileage',
            field=models.IntegerField(blank=True, help_text='Odometer reading in km', null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='mileage_adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='ownership',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd+', '3rd owner or more')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='service_records',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
