# Generated by Django 6.1 on 2026-08-25 14:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_lead_source_alter_lead_accident_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportEnquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(choices=[('website', 'Website'), ('seller', 'Seller'), ('dealer', 'Dealer')], default='website', max_length=20)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Support Enquiry',
                'verbose_name_plural': 'Support Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
